### ISSUE TITLE
Fill the [package] section of Cargo.toml

### ISSUE THREAD

**Issue by girvel** [girvel/routine-bender#4]
Example:
```toml
[package]
name = "grrs"
version = "0.1.0"
authors = ["Your Name <your@email.com>"]
license = "MIT OR Apache-2.0"
description = "A tool to search files"
readme = "README.md"
homepage = "https://github.com/you/grrs"
repository = "https://github.com/you/grrs"
keywords = ["cli", "search", "demo"]
categories = ["command-line-utilities"]
```
